In [1]:
import numpy as np

In [2]:
mu, sigma = 10, 0.1 # mean and standard deviation
s = np.random.default_rng().normal(mu, sigma, size=(20000,20000))
s

array([[10.05672981,  9.85403367,  9.8934442 , ..., 10.08305177,
         9.96851715,  9.93542352],
       [ 9.94075092,  9.95269821, 10.20229967, ..., 10.05211552,
        10.12340301,  9.99319486],
       [10.00518062, 10.14100514,  9.88922782, ..., 10.09084219,
         9.96532059, 10.06396124],
       ...,
       [10.06061514, 10.10733832, 10.05457414, ...,  9.99900326,
        10.01774668, 10.02605638],
       [10.06722393, 10.0136125 , 10.09875139, ...,  9.97547125,
        10.06405918, 10.1134673 ],
       [10.00040618,  9.90973527,  9.94882607, ...,  9.81721421,
        10.02116003,  9.96351148]])

In [3]:
y= s 
%time z=y[::100,:].mean(axis=0)
z

Wall time: 5.96 ms


array([10.00149472, 10.00378532, 10.00775953, ...,  9.9871711 ,
        9.99251958,  9.995388  ])

In [4]:
#!pip install dask-labextension

In [5]:
# Start Dask Client for Dashboard
from dask.distributed import Client, progress
client = Client(processes=False, threads_per_worker=4,
                n_workers=1, memory_limit='9GB')
client

<Client: 'inproc://10.110.229.215/11316/1' processes=1 threads=4, memory=9.00 GB>

In [6]:
import dask.array as da
x = da.from_array(s, chunks=(1000,1000))

In [7]:
y= x 
z=y[::100,:].mean(axis=0)
z

dask.array<mean_agg-aggregate, shape=(20000,), dtype=float64, chunksize=(1000,), chunktype=numpy.ndarray>

In [8]:
z.compute()


distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 6.49 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 6.54 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARNING - Worker is at 108% memory usage. Pausing worker.  Process memory: 9.75 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 9.75 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARNING - Worker is at 13% memory usage. Resuming worker. Process memory: 1.20 GB -- Worker memory limit: 9.00 GB


array([10.00149472, 10.00378532, 10.00775953, ...,  9.9871711 ,
        9.99251958,  9.995388  ])

In [ ]:
%time 
z.compute()

Wall time: 0 ns


distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 6.46 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARNING - Worker is at 108% memory usage. Pausing worker.  Process memory: 9.73 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 9.73 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 11.40 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 7.88 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store t

distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 7.88 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 7.88 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 7.88 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 7.88 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 7.88 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARN

distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 7.88 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 7.88 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 7.88 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 7.88 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 7.88 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARN

distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 7.88 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 7.88 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 7.88 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 7.88 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 7.88 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARN

distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 7.88 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 7.88 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 7.88 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 7.88 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 7.88 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARN

distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 7.88 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 7.88 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 7.88 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 7.88 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 7.88 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARN

distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 7.88 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 7.88 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 7.88 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 7.88 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 7.88 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARN

distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 7.88 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 7.88 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 7.88 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 7.88 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 7.88 GB -- Worker memory limit: 9.00 GB
distributed.worker - WARN